### ISSUE TITLE
Multiple structures uploader

### ISSUE THREAD

**Issue by yakutovicha** [materialscloud-org/mc-aiida-widgets#3]
I've been recently reviewing tools to select and upload several structures at one shot. Unfortunately, even though it is considered useful, neither [fileupload](https://github.com/peteut/ipython-file-upload) nor [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) do currently provide such multi upload functionality. Then I looked closely to those packages trying to understand if this was somehow considered.

First I looked at fileuploader package that we use quite extensively. Unfortunately, even though the possibility to upload multiple files was [considered useful](https://github.com/peteut/ipython-file-upload/issues/5) and people actually [started working on that](https://github.com/peteut/ipython-file-upload/issues/22#issuecomment-351028737), it looks to me that no significant progress was made in this direction.

Second I looked at [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) and discovered that there is a [long-standing discussion](https://github.com/jupyter-widgets/ipywidgets/issues/1542) about adding both: file upload and multiple file upload features to the package. A [PR](https://github.com/jupyter-widgets/ipywidgets/pull/2211) have been created and is still under review process. So we should wait until it will be finally approved.

Therefore, for the moment I will go standard way: uploading an archive file that contains structures, unpack them and store one by one in AiiDA.

**Comment by ltalirz** [comment]
Added in e3002c5b931654b51d9ec6a7b58549c7316771b4
